version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
        MONGO_INITDB_ROOT_DATABASENAME: test
    networks:
      - backend
volumes:
  db:
networks:
  backend:
